#!/bin/bash
#_______________________________________#
#Author: Vasanth
#_______________________________________#
#Description: To find the word localhost through the /etc
#_______________________________________#
#Date: Wednesday 14 April 2021 06:22:16 PM IST
#_______________________________________#



grep  -R localhost /etc/* | awk '{print $1}' > /tmp/find.out 
grep -q localhost /etc/* 2>/tmp/find.err 
echo FILE OUTPUT SAVED
echo FILE ERROR SAVED

